version: "3"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: simplebank
    ports:
      - "5432:5432"
